// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Address, DataSourceTemplate, DataSourceContext } from '@graphprotocol/graph-ts'

export class xERC20 extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create('xERC20', [address.toHex()])
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext('xERC20', [address.toHex()], context)
  }
}
